#!/usr/bin/env python
# -*- coding: utf-8 -*-

# tools/cache
# Copyright (c) 2007 Zero Piraeus <z@hojarama.org>
#
# This file is part of Hojarama [release 0.08.01].
#
# Hojarama is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# Hojarama is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

"""Cache all indexed pages."""

import os
import sys

sys.path.append(os.path.abspath(os.path.join(sys.path[0], os.pardir, "hr")))

from hojarama import Persistent

from Index import Index
from Languages import Languages
from Page import Page


if __name__ == "__main__":
    Persistent.reset_cache()
    for lang_id in Languages().visible:
        for record in Index(lang_id):
            Page(record.node, lang_id).xhtml()

