#!/usr/bin/env python
# -*- coding: utf-8 -*-

# tools/config
# Copyright (c) 2007 Zero Piraeus <z@hojarama.org>
#
# This file is part of Hojarama [release 0.08.01].
#
# Hojarama is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# Hojarama is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

"""Manage the site configuration."""

import os
import sys

sys.path.append(os.path.abspath(os.path.join(sys.path[0], os.pardir, "hr")))

from hrtools import run_parser

from Config import Config

META = ({"name": "OPT",
         "help": "Configuration option",
         "example": "name"},

        {"name": "VAL",
         "help": "Configuration value",
         "example": "yes"},

        {"name": "PREF",
         "help": "OPT:VAL",
         "example": "log:warning"})

SPEC = (("d", "defaults", None, "display the default configuration values"),
        ("l", "list", None, "list all options"),
        ("r", "reset", "OPT", "reset option OPT to its default value"),
        ("s", "set", "PREF", "set option OPT to VAL"))


if __name__ == "__main__":
    run_parser("config", Config(), SPEC, META)

