#!/usr/bin/env python
# -*- coding: utf-8 -*-

# tools/translations
# Copyright (c) 2007 Zero Piraeus <z@hojarama.org>
#
# This file is part of Hojarama [release 0.08.01].
#
# Hojarama is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# Hojarama is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

"""Manage the site translations."""

import os
import sys

sys.path.append(os.path.abspath(os.path.join(sys.path[0], os.pardir, "hr")))

from hrtools import run_parser

from Translations import Translations

META = ({"name": "KEY",
         "help": "The term to translate",
         "example": "next_prefix"},

        {"name": "LANG",
         "help": "ISO-639-1 language identifier",
         "example": "it"},

        {"name": "VAL",
         "help": "Translation of the term",
         "example": "You are here: "},

        {"name": "TRAN",
         "help": "KEY:LANG:VAL",
         "example": "nav_title:en:Navigation"})

SPEC = (("a", "add", "KEY", "add the term KEY"),
        ("k", "kill", "KEY", "permanently delete the term KEY"),
        ("l", "list", None, "list all translations"),
        ("s", "set", "TRAN", "set translation LANG of KEY to VAL"))


if __name__ == "__main__":
    run_parser("translations", Translations(), SPEC, META, confirm="k")

